name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        name: Setup Rust
        
      - name: brndnmtthws/rust-action-rustup
        # You may pin to the exact commit or the version.
        # uses: brndnmtthws/rust-action-rustup@bf5d3fa33a16dddad2e0fe9a84439486182a9803
        uses: brndnmtthws/rust-action-rustup@v1.0.0
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
          
      - name: wasm-pack-action
        # You may pin to the exact commit or the version.
        # uses: jetli/wasm-pack-action@0d096b08b4e5a7de8c28de67e11e945404e9eefa
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          # Optional version of wasm-pack to install (eg. "v0.9.1", "latest")
          version: # optional, default is latest

      - name: wasm-bindgen-action
        # You may pin to the exact commit or the version.
        # uses: jetli/wasm-bindgen-action@20b33e20595891ab1a0ed73145d8a21fc96e7c29
        uses: jetli/wasm-bindgen-action@v0.2.0
        with:
          # Optional version of wasm-bindgen to install (eg. "0.2.68", "latest")
          version: # optional, default is latest


      - run: wasm-pack build --target web 
        name: Build WASM

      - run: cp ./pkg/ ./site/pkg/ -R
        name: Copy WASM

      - run: cp ./favicon.ico ./site/ 
        name: Copy favicon

      - run: cp ./index.html ./site/ 
        name: Copy favicon

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_FLOWER_0F2636710 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          skip_app_build: true
          app_location: "/site" 
          api_location: "" 
          output_location: "" 

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_FLOWER_0F2636710 }}
          action: "close"
